[package]
name = "pk_secp256k1_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.32.5"
clap = { version = "4.5.26", features = ["derive"] }
hex = "0.4.3"
rand = "0.8.5"
secp256k1 = { version = "0.30.0", features = [ "rand", "global-context" ] }
